apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-microservice-deployment
spec:
  replicas: 1
  selector:
     matchLabels:
       app: mssql-microservice
  template:
    metadata:
      labels:
        app: mssql-microservice
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mssqlinst
      securityContext:
        fsGroup: 10001
      containers:
      - name: mssql-microservice
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: microservice-server-configmap
              key: password
        volumeMounts:
        - name: mssql-microservice-persistent-storage
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-microservice-persistent-storage
        persistentVolumeClaim:
          claimName: mssql-microservice-data-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-microservice-service
spec:
  selector:
    app: mssql-microservice
  ports:
    - protocol: TCP
      port: 1402
      targetPort: 1433
  type: LoadBalancer